### ISSUE TITLE
Textarea pastes are broken in Edge

### ISSUE THREAD

**Issue by pkaminski** [layerssss/paste.js#25] opened 2016-03-23 22:00 UTC
Pasting text into a `textarea` in Edge (25.10586.0.0) inserts the clipboard (i) twice and (ii) at the beginning of the text no matter where the cursor is.  Easily reproducible at http://micy.in/paste.js/.

reviewable/reviewable#267

**Comment by layerssss** [comment] 2016-09-06 11:22
Hi @pkaminski  I can confirm that:

1. it's because of two buggy patches accidentally been pushed to my `gh-pages` branch
2. at this moment it's working fine on latest Edge (the same version string!)

And now the 'text' focusing issue is fixed by updating that branch. And image pasting on Edge is working now because of the new patch.

**Closed by layerssss** 2016-09-06 11:22 UTC
