### ISSUE TITLE
Image paste doesn't work for pastableTextarea in firefox

### ISSUE THREAD

**Issue by xdumaine** [layerssss/paste.js#11] opened 2015-05-05 20:44 UTC
On the example page and in my app, I can paste an image into the pastableNonInputable and pastableContenteditable but not pastableTextarea only in firefox. Pasting image in pastableTextarea works in Chrome

**Comment by layerssss** [comment] 2015-05-07 06:03
Thanks for submitting the issue, I'll look into the problem today

**Comment by jmuheim** [comment] 2015-06-18 07:37
Does work for me on both OSX 10.10 / Windows 7 and FF 38.0.5 Did you succeed in the meantime?

**Comment by layerssss** [comment] 2015-06-18 09:10
works for me too, (osx/ FF 38). The current hack for firefox consist of brutal key detection, listens to the `keydown/keyup` events, check the `keyCode` and `ctlDown` status, so it should be fragile in possible edge cases. So it would really help if someone finds the edge cases and report the environment (if possible keymap? anyway I am using dvorak keymap and experienced no problem).

**Comment by jmuheim** [comment] 2015-06-18 09:24
That's good to hear. Anyway, it would be nice to sort this out. I'm using QWERTY.

**Comment by layerssss** [comment] 2015-06-18 09:30
@jmuheim so we both can not reproduce this problem, right? if so let's close this issue to see later if anyone come up with a new one.

**Closed by layerssss** 2015-06-18 09:30 UTC
